version: "3"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: Dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080