version: "2.1"
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: Emby
    labels:
      - com.centurylinklabs.watchtower.enable=true #Label pour mise à jour automatique avec watchtower.
    environment:
      - PUID= #Votre PUID
      - PGID= #Votre PGID
      - TZ=Europe/Paris
    volumes:
      - ./Emby:/config            #Renseignez le dossier où vous souhaitez que votre configuration se trouve.
      - ./Series:/data/tvshows    #Renseignez l'emplacement de votre dossier de Séries.
      - ./Films:/data/movies      #Renseignez l'emplacement de votre dossier de Films.
    ports:
      - 8096:8096
    restart: unless-stopped