version: "2.1"
services:
  embystat:
    image: lscr.io/linuxserver/embystat:latest
    container_name: EmbyStat
    labels:
      - com.centurylinklabs.watchtower.enable=true #Label pour mise à jour automatique avec watchtower.
    environment:
      - PUID= #Votre PUID
      - PGID= #Votre PGID
      - TZ=Europe/Paris
    volumes:
      - ./EmbyStat:/config #Renseignez le dossier où vous souhaitez que votre configuration se trouve.
    ports:
      - 6555:6555
    restart: unless-stopped