version: '3.9'
services:
    server:
        image: gotify/server:latest
        labels:
            - com.centurylinklabs.watchtower.enable=true #Label pour mise à jour automatique avec watchtower.
        volumes:
            - ./Gotify:/app/data #Renseignez le dossier où vous souhaitez que votre configuration se trouve.
        ports:
            - 8080:80 #Vous pouvez remplacer le premier 8080 par le port de votre choix.