version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: Heimdall
    labels:
      - com.centurylinklabs.watchtower.enable=true #Label pour mise à jour automatique avec watchtower.
    environment:
      - PUID= #Votre PUID
      - PGID= #Votre PGID
      - TZ=Europe/Paris
    volumes:
      - ./Heimdall:/config #Renseignez le dossier où vous souhaitez que votre configuration se trouve.
    ports:
      - 8080:80
      - 4443:443
    restart: unless-stopped