version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: Transmission
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=   #Votre PUID
      - PGID=   #Votre PGID
      - TZ=Europe/Paris
      - USER=   #Identifiant accès Web.
      - PASS=   #Mot de passe accès Web.
    volumes:
      - ./Transmission:/config #Renseignez le dossier où vous souhaitez que votre configuration se trouve.
      - ./Terminer:/downloads  #Renseignez le dossier où vous souhaitez que vos téléchargements ce stock.
      - ./En_cours:/watch      #Renseignez le dossier où vous souhaitez que vos téléchargements en cours ce stock.
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped