---
version: "2.1"
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: WikiJS
    labels:
      - com.centurylinklabs.watchtower.enable=true #Label pour mise à jour automatique avec watchtower.
    environment:
      - PUID= #Votre PUID
      - PGID= #Votre PGID
      - TZ=Europe/Paris
    volumes:
      - ./WikiJS/config:/config #Renseignez le dossier où vous souhaitez que votre configuration se trouve.
      - ./WikiJS/data:/data     #Renseignez le dossier où vous souhaitez que vos données se trouvent.
    ports:
      - 3000:3000
    restart: unless-stopped